name: Build Godot Project and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      # 匯出 Godot HTML5
      - name: Build Godot HTML5
        id: build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: example
          preset: HTML5    # ⚠️ 改成你 Godot 預設裡的 HTML5 export preset 名稱
          debugMode: "false"

      # 上傳 Artifact（可選，用於除錯下載）
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Godot-HTML5
          path: ${{ steps.build.outputs.build }}

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.build.outputs.build }}
